### ISSUE TITLE
Newlib: build fails with error: comparison of unsigned expression in '>= 0' 

### ISSUE THREAD

**Issue by temap** [foss-for-synopsys-dwc-arc-processors/gcc#102] opened 2021-09-28 14:32 UTC
When toolchain is built without `--disable-werror`, the build fails with the following error:
```
ctype_members.cc: In member function 'virtual char std::ctype<wchar_t>::do_narrow(wchar_t, char) const':
ctype_members.cc:216:14: error: comparison of unsigned expression in '>= 0' is always true [-Werror=type-limits]
  216 |     if (__wc >= 0 && __wc < 128 && _M_narrow_ok)
      |         ~~~~~^~~~
ctype_members.cc: In member function 'virtual const wchar_t* std::ctype<wchar_t>::do_narrow(const wchar_t*, const wchar_t*, char, char*) const':
ctype_members.cc:230:21: error: comparison of unsigned expression in '>= 0' is always true [-Werror=type-limits]
  230 |           if (*__lo >= 0 && *__lo < 128)
      |               ~~~~~~^~~~
cc1plus: all warnings being treated as errors
make[6]: *** [Makefile:648: ctype_members.lo] Error 1
```

**Comment by shahab-vahedi** [comment] 2021-10-07 09:24
I know it is cumbersome to find an issue in this plethora of repositories, but this is already a duplicate of [arc64/42](foss-for-synopsys-dwc-arc-processors/toolchain#459). Please check that for updates.

**Closed as completed by shahab-vahedi** 2021-10-07 09:24 UTC
Labels: bug, arc64

**Comment by temap** [comment] 2021-10-07 12:09
@shahab-vahedi, should I create arc64 related issues in https://github.com/foss-for-synopsys-dwc-arc-processors/arc64?
I thought we already passed the initial bring-up phase.

**Comment by shahab-vahedi** [comment] 2021-10-07 15:59
Not anymore, that particular issue was created in Mar-2021.
